name: Deploy to GH pages

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Node versions
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install
        run: npm i

      - name: Linter
        run: npm run linter

      - name: Test
        run: npm run test

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: lint_and_test

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm i

      - name: Configure GH pages
        uses: actions/configure-pages@v3

      - name: Tailwind
        run: npm run design

      - name: Compile TS in JS
        run: npm run compile

      - name: Copy index.html in dist folder
        run: cp index.html ./dist/

      - name: Copy fonts in dist
        run: cp -r ./public/assets/fonts ./dist/public/assets/fonts

      - name: Copy images in dist
        run: cp -r ./public/assets/images ./dist/public/assets/images

      - name: Uploading artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist/

      - name: Deploy to GH pages
        uses: actions/deploy-pages@v1
        id: deployment
